name: uanav
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.1
  flutter_map: ^8.1.1
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  shared_preferences: ^2.5.5
  supabase_flutter: ^2.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - map_data/node.json
    - map_data/edge.json
    - map_data/place.json
